// @generated by design-tokens/gen.mjs — DO NOT EDIT BY HAND.
// Edit design-tokens/status.json, then run `node design-tokens/gen.mjs`.
// CI (`gen.mjs --check`) fails on drift.
//
// Work-state semantics are presentation data derived from WorkView.work_state.
// Client palettes resolve semantic roles to their own foreground/background styles.
// This module intentionally contains no color values or transport fields.

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum WorkSemanticRole {
    Info,
    Accent,
    Warning,
    Danger,
    Neutral,
}

impl WorkSemanticRole {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Info => "info",
            Self::Accent => "accent",
            Self::Warning => "warning",
            Self::Danger => "danger",
            Self::Neutral => "neutral",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct WorkStatusSemantics {
    pub state: &'static str,
    pub label: &'static str,
    pub semantic_role: WorkSemanticRole,
    pub observed_running_count: u8,
    pub observed_succeeded_count: u8,
}

pub const WORK_STATUS_SEMANTICS: &[WorkStatusSemantics] = &[
    WorkStatusSemantics {
        state: "queued",
        label: "Queued",
        semantic_role: WorkSemanticRole::Info,
        observed_running_count: 0,
        observed_succeeded_count: 0,
    },
    WorkStatusSemantics {
        state: "running",
        label: "Running",
        semantic_role: WorkSemanticRole::Info,
        observed_running_count: 1,
        observed_succeeded_count: 0,
    },
    WorkStatusSemantics {
        state: "waiting_children",
        label: "Waiting for child work",
        semantic_role: WorkSemanticRole::Warning,
        observed_running_count: 0,
        observed_succeeded_count: 0,
    },
    WorkStatusSemantics {
        state: "succeeded",
        label: "Succeeded",
        semantic_role: WorkSemanticRole::Accent,
        observed_running_count: 0,
        observed_succeeded_count: 1,
    },
    WorkStatusSemantics {
        state: "failed",
        label: "Failed",
        semantic_role: WorkSemanticRole::Danger,
        observed_running_count: 0,
        observed_succeeded_count: 0,
    },
    WorkStatusSemantics {
        state: "reconcile",
        label: "Reconciling",
        semantic_role: WorkSemanticRole::Warning,
        observed_running_count: 0,
        observed_succeeded_count: 0,
    },
    WorkStatusSemantics {
        state: "cancelled",
        label: "Cancelled",
        semantic_role: WorkSemanticRole::Neutral,
        observed_running_count: 0,
        observed_succeeded_count: 0,
    },
];

pub fn work_status_semantics(state: &str) -> Option<&'static WorkStatusSemantics> {
    WORK_STATUS_SEMANTICS
        .iter()
        .find(|semantics| semantics.state == state)
}

#[cfg(test)]
mod tests {
    use super::{work_status_semantics, WorkSemanticRole, WORK_STATUS_SEMANTICS};

    #[test]
    fn generated_work_status_semantics_are_lookupable() {
        assert_eq!(WORK_STATUS_SEMANTICS.len(), 7);
        let running = work_status_semantics("running").expect("running must be generated");
        assert_eq!(running.semantic_role, WorkSemanticRole::Info);
        assert_eq!(
            (
                running.observed_running_count,
                running.observed_succeeded_count
            ),
            (1, 0)
        );
        assert!(work_status_semantics("unknown").is_none());
    }
}
