// @generated by design-tokens/gen.mjs — DO NOT EDIT BY HAND.
// Edit design-tokens/tokens.json or design-tokens/status.json, then run
// `node design-tokens/gen.mjs`. CI (`gen.mjs --check`) fails on drift.
//
// Work-state semantics are presentation data derived from WorkView.work_state.
// Client palettes resolve semantic roles to their own foreground/background styles.
// This module intentionally contains no color values or transport fields.

export type WorkState =
  | "queued"
  | "running"
  | "waiting_children"
  | "succeeded"
  | "failed"
  | "reconcile"
  | "cancelled";

export type WorkSemanticRole =
  | "info"
  | "accent"
  | "warning"
  | "danger"
  | "neutral";

export interface WorkStatusSemantics {
  readonly state: WorkState;
  readonly label: string;
  readonly semanticRole: WorkSemanticRole;
  readonly observedRunningCount: 0 | 1;
  readonly observedSucceededCount: 0 | 1;
}

export const WORK_STATUS_SEMANTICS: readonly WorkStatusSemantics[] = [
  { state: "queued", label: "Queued", semanticRole: "info", observedRunningCount: 0, observedSucceededCount: 0 },
  { state: "running", label: "Running", semanticRole: "info", observedRunningCount: 1, observedSucceededCount: 0 },
  { state: "waiting_children", label: "Waiting for child work", semanticRole: "warning", observedRunningCount: 0, observedSucceededCount: 0 },
  { state: "succeeded", label: "Succeeded", semanticRole: "accent", observedRunningCount: 0, observedSucceededCount: 1 },
  { state: "failed", label: "Failed", semanticRole: "danger", observedRunningCount: 0, observedSucceededCount: 0 },
  { state: "reconcile", label: "Reconciling", semanticRole: "warning", observedRunningCount: 0, observedSucceededCount: 0 },
  { state: "cancelled", label: "Cancelled", semanticRole: "neutral", observedRunningCount: 0, observedSucceededCount: 0 },
];

export function workStatusSemantics(state: string): WorkStatusSemantics | undefined {
  return WORK_STATUS_SEMANTICS.find((semantics) => semantics.state === state);
}
